const data = [
    {
        img:'https://www.pngfind.com/pngs/m/173-1737582_1000-x-972-71-4-business-man-with.png',
        Name:'Spider',
        Age:'45',
        Type:'white-hat',
        Garenty:'No',
        Cost:20000
    },
    {
        img:'https://www.nicepng.com/png/full/256-2561738_men-photo-png.png',
        Name:'wax',
        Age:'45',
        Type:'black-hat',
        Garenty:'yes',
        Cost:60000
    },
    {
        img:'https://pngimg.com/uploads/man/man_PNG6534.png',
        Name:'Riper',
        Age:'25',
        Type:'white-hat',
        Garenty:'No',
        Cost:30000
    },
    {
        img:'https://www.pngarts.com/files/1/Formal-Suit-For-Men-PNG-Transparent-Image.png',
        Name:'pid',
        Age:'35',
        Type:'white-hat',
        Garenty:'No',
        Cost:20000
    },
    {
        img:'https://cdn.shopify.com/s/files/1/0310/3571/9739/files/Best_Male_Model_Poses_for_Men_-_Male_Standing_Poses_-_Sunny_16_1024x1024.jpg?v=1592613103',
        Name:'Rex',
        Age:'45',
        Type:'black-hat',
        Garenty:'yes',
        Cost:50000
    },
    {
        img:'https://www.pngkit.com/png/full/57-576353_free-png-happy-men-png-images-transparent-transparent.png',
        Name:'Sprk',
        Age:'40',
        Type:'Brown-hat',
        Garenty:'No',
        Cost:10000
    },
    {
        img:'https://www.seekpng.com/png/full/74-747179_best-free-men-suit-png-image-man-in.png',
        Name:'givx',
        Age:'40',
        Type:'black-hat',
        Garenty:'yes',
        Cost:60000
    },
    {
        img:'https://www.freepnglogos.com/uploads/man-png/man-attitude-pro-9.png',
        Name:'max',
        Age:'64',
        Type:'black-hat',
        Garenty:'yes',
        Cost:60000
    },
    {
        img:'https://www.freepnglogos.com/uploads/man-png/man-png-transparent-images-png-only-8.png',
        Name:'bim',
        Age:'25',
        Type:'brown-hat',
        Garenty:'yes',
        Cost:60000
    },

]